# Generated by Django 2.0.4 on 2018-05-05 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=246)),
                ('mname', models.CharField(max_length=246)),
                ('lname', models.CharField(max_length=246)),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], default='m', max_length=6)),
                ('dob', models.DateField()),
            ],
        ),
    ]
