# Generated by Django 2.0.4 on 2018-05-05 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='mname',
            field=models.CharField(blank=True, max_length=246),
        ),
    ]
